# Port
server.port=8080

# MySQL database
# Make new db if not exist
spring.datasource.url=jdbc:mysql://localhost:3306/mot_reminder_db?createDatabaseIfNotExist=true&serverTimezone=UTC

# Login
spring.datasource.username=root
spring.datasource.password=root

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Email setup
spring.mail.host=smtp.seznam.cz
spring.mail.port=465
spring.mail.username=mot.reminder.pacalt@seznam.cz
spring.mail.password=Pacaltik007
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.ssl.enable=true